# Generated by Django 3.2.15 on 2022-10-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
